config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index'

  root to: 'events#index'
  resources :events do 
    resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event

  validates :msg, :author, presence: true 

  validates_length_of :msg, maximum: 140

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, -> { order :created_at }, dependent: :destroy

  validates :name, :date, :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  validates_length_of :name, maximum: 60
  validates_length_of :description, maximum: 60
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Event.find(params[:event_id]).comments.new(comment_params)
    if @comment.save
      redirect_to event_path(@comment.event)
    else
      @event = @comment.event
      render :template => "events/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:author, :msg)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    order_params = params[:order].present? ? params[:order] : :name

    @events = Event.where(
      'date >= ?', Date.today - 10.days
    ).order(order_params)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end
    

  private
  def event_params
    params.require(:event).permit(:name, :date, :description, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'panel panel-danger') do
        concat(content_tag(:div, class: 'panel-heading') do
          concat(content_tag(:h4, class: 'panel-title') do
            concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: 'panel-body') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
  def event_class_color(event)
    if event.date.past?
      'table-secondary'
    elsif Date.today + 10.days > event.date
      'table-danger'
    else
      'table-dark'
    end
  end
end

app/views/events/_form.html.erb
<div class="form">
    
  <%= form_for(@event) do |f| %>

    <%= errors_for(@event) %>
    <div class="field-wrap">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', placeholder: "Event name"%>
    </div>
    <div class="field-wrap">
      <%= f.label :email %><br>
      <%= f.text_field :email, type: 'email', class: 'form-control', placeholder: "Author's email"%>
    </div>
    <div class="field-wrap">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control', placeholder: "Event description"%>
    </div>
     <div class="field-wrap">
      <%= f.label :date %><br>
      <%= f.date_select :date%>
    </div>
    <div class="actions">
      <%= f.submit 'Save', class:'btn btn-info' %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container"  >

  <div class="row">
    <h1>Welcome to new event manager</h1>
  </div>
  <div class="row" style="margin-bottom: 10px;">
    <a href=<%= new_event_path %> class="btn btn-info" role="button">
      <i class="fa fa-plus" aria-hidden="true"></i>
      Add event
    </a>
  </div>  

  <div class="row">
    <div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort by
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <a class="dropdown-item" href="<%= events_path(order: 'date') %>">Date</a>
      <a class="dropdown-item" href="<%= events_path(order: 'name') %>">Names</a>
      <a class="dropdown-item" href="<%= events_path(order: 'email') %>">Email</a>
    </div>
  </div>


  <table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
      <tr>
        <th class="th-sm">Name</th>
        <th class="th-sm">Description</th>
        <th class="th-sm">Email</th>
        <th class="th-sm">Date</th>
        <th class="th-sm">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr class="<%=event_class_color(event)%>">
          <td ><%= event.name %></td>
          <td><%= event.description %></td>
          <td><%= event.email %></td>
          <td><%= event.date %></td>
          <td>
            <a href=<%= event_path(event) %> class="btn btn-info" role="button">View</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<div class="container">
  <%= link_to 'Back', events_path, class: 'btn btn-danger' %>
  <h1>New Event</h1>

  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
  <%= link_to 'Back to events', events_path, class: 'btn btn-danger' %>
  </div>
  <div>
    <div class="row">
      <h1>Name: <%= @event.name %></h1>
    </div>
    <div class="row">
      <h2>Email: <%=@event.email %></h2>
    </div>
    <div class="row">
      <h2>Descrition: <%=@event.description %></h2>
    </div>
    <div class="row">
      <h2>Date: <%=@event.date %></h2>
    </div>
  </div>
  <% if @event.comments.count > 0 %>
  <table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
      <tr>
        <th class="th-sm">Created time</th>
        <th class="th-lg">Author</th>
        <th class="th-lg">Message</th>
      </tr>
    </thead>
    <tbody>
      <% @event.comments.each do |comment| %>
        <tr>
          <td><%= time_ago_in_words(comment.created_at) %> ago</td>
          <td><%= comment.author %></td>
          <td><%= comment.msg %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% else %>
    <h2>No comment yet</h2>
  <% end %>
  <div class="row">
    <h>Add new comment</h3>
  </div>
  <div class="row">
    <div class="form">
    <%= form_for(@comment, url: event_comments_path(@event.id)) do |f| %>

      <%= errors_for(@comment) %>
      <div class="field-wrap">
        <%= f.label :author %><br>
        <%= f.text_field :author,class: 'form-control', placeholder: "Author's name"%>
      </div>
      <div class="field-wrap">
        <%= f.label :msg %><br>
        <%= f.text_area :msg, class: 'form-control', placeholder: "Comment"%>
      </div>
      <div class="actions">
        <%= f.submit 'Save', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
</div>  



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evento</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Evento</h5>
    </div>

    <%= yield %>
  </body>
</html>